### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by mblarsen** [beyonk-adventures/svelte-scrollspy#1]
Error loading @beyonk/svelte-scrollspy/src/ScrollableSection.html from bundle.run

**Comment by antony** [comment]
@mblarsen bundle.run is a fickle beast :) not sure I can do too much about this.

**Comment by mblarsen** [comment]
If the demo isn't working then perhaps remove it.

**Comment by antony** [comment]
@mblarsen it's removed as part of the upgrade. It's not that it wasn't working per-se, bundle.run is fickle, so sometimes it works, sometimes it doesn't.
